# permissions for end users to view dlrnapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlrnapi-viewer-role
rules:
- apiGroups:
  - dlrn.example.com
  resources:
  - dlrnapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dlrn.example.com
  resources:
  - dlrnapis/status
  verbs:
  - get
