# permissions for end users to edit dlrnapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dlrnapi-editor-role
rules:
- apiGroups:
  - dlrn.example.com
  resources:
  - dlrnapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dlrn.example.com
  resources:
  - dlrnapis/status
  verbs:
  - get
